#!/bin/bash
# Waydroid 初始化指南（交互式提示）
set -e

echo "=== Waydroid Setup Guide ==="
echo ""
echo "1. 安装 Waydroid（Ubuntu 22.04）："
echo "   curl -s https://repo.waydro.id/waydroid.gpg | sudo tee /usr/share/keyrings/waydroid.gpg > /dev/null"
echo "   echo 'deb [signed-by=/usr/share/keyrings/waydroid.gpg] https://repo.waydro.id/ jammy main' | sudo tee /etc/apt/sources.list.d/waydroid.list"
echo "   sudo apt update && sudo apt install waydroid"
echo ""
echo "2. 初始化（选 GAPPS 镜像以获得 Play Store，或选 VANILLA）："
echo "   sudo waydroid init -s GAPPS"
echo ""
echo "3. 启动 session："
echo "   waydroid session start"
echo ""
echo "4. 安装微信 APK（ARM64 版本，从官网下载）："
echo "   adb connect 192.168.240.1:5555"
echo "   adb install -r weixin.apk"
echo ""
echo "5. 手动登录微信（只需一次）。"
echo ""
echo "6. 安装 WechatBridge APK："
echo "   cd $(dirname "$0")/../apk && ./gradlew assembleDebug"
echo "   adb install -r app/build/outputs/apk/debug/app-debug.apk"
echo ""
echo "7. 启用 Accessibility Service："
echo "   adb shell settings put secure enabled_accessibility_services com.wechatbridge/.WechatAccessibilityService"
echo "   adb shell settings put secure accessibility_enabled 1"
echo ""
echo "8. 建立 port forward："
echo "   bash $(dirname "$0")/setup_adb_forward.sh"
echo ""
echo "完成后运行 'make health' 验证所有组件状态。"
